# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Enuma Technologies
email: blog@enuma.io
description: > # this means to ignore newlines until "baseurl:"
  Enuma Technologies is an engineering firm focused on building
  software and hardware solutions. You have an idea, we can implement
  it. You have a problem, we will solve it. Our team is composed of
  engineers with many years of experience working in different
  companies, from startups to large enterprises including Microsoft.
  We have a proven track record delivering robust, scalable and
  secure solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.enuma.io" # the base hostname & protocol for your site
twitter_username: enumatech
github_username:  enumatech
facebook_username:  enumatech

# Build settings
markdown: kramdown
